export const conditionTypes = {
    clear: 'Ясно',
    'partly-cloudy': 'Малооблачно',
    cloudy: 'Облачно с прояснениями',
    overcast: 'Пасмурно',
    drizzle: 'Морось',
    'light-rain': 'Небольшой дождь',
    rain: 'Дождь',
    'moderate-rain': 'Умеренно сильный дождь',
    'heavy-rain': 'Сильный дождь',
    'continuous-heavy-rain': 'Длительный сильный дождь',
    showers: 'Ливень',
    'wet-snow': 'Дождь со снегом',
    'light-snow': 'Небольшой снег',
    snow: 'Снег',
    'snow-showers': 'Снегопад',
    hail: 'Град',
    thunderstorm: 'Гроза',
    'thunderstorm-with-rain': 'Дождь с грозой',
    'thunderstorm-with-hail': 'Гроза с градом',
};

export const windDirectionsFull = {
    nw: 'северо-западное',
    n: 'северное',
    ne: 'северо-восточное',
    e: 'восточное',
    se: 'юго-восточное',
    s: 'южное',
    sw: 'юго-западное',
    w: 'западное',
    c: 'штиль',
};

export const windDirectionsShort = {
    nw: 'СЗ',
    n: 'С',
    ne: 'СВ',
    e: 'В',
    se: 'ЮВ',
    s: 'Ю',
    sw: 'ЮЗ',
    w: 'З',
    c: '',
};
